allowBuilds:
  sharp: true
minimumReleaseAgeExclude:
  - '@clerk/backend@3.11.7'
  - '@clerk/nextjs@7.5.20'
  - '@clerk/react@6.12.5'
  - '@clerk/shared@4.25.5'
  - '@tailwindcss/node@4.3.3'
  - '@tailwindcss/oxide-android-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-arm64@4.3.3'
  - '@tailwindcss/oxide-darwin-x64@4.3.3'
  - '@tailwindcss/oxide-freebsd-x64@4.3.3'
  - '@tailwindcss/oxide-linux-arm-gnueabihf@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-arm64-musl@4.3.3'
  - '@tailwindcss/oxide-linux-x64-gnu@4.3.3'
  - '@tailwindcss/oxide-linux-x64-musl@4.3.3'
  - '@tailwindcss/oxide-wasm32-wasi@4.3.3'
  - '@tailwindcss/oxide-win32-arm64-msvc@4.3.3'
  - '@tailwindcss/oxide-win32-x64-msvc@4.3.3'
  - '@tailwindcss/oxide@4.3.3'
  - '@tailwindcss/postcss@4.3.3'
  - tailwindcss@4.3.3
